### ISSUE TITLE
Externalize project key & base url

### ISSUE THREAD

**Issue by jprusch** [Thomas-Gelf/icingaweb2-module-jira#3]
Hi Thomas,

amazing module: Wonderful integration!

It would be great to get some parameters externalize or configurable. I had to modify the RestApi.php:

```
protected function prepareIssueQuery($host = null, $service = null, $onlyOpen = true)
    {
        $project = 'PROJECTKEY';

        $query = sprintf('project = "%s" AND creator = currentUser()', $project);

        if ($onlyOpen) {
            // TODO: make this either configurable or ask JIRA
            $query .= ' **AND resolution IS EMPTY**';
        }
```

to make the query independent of status names. Nice: You already marked it as TODO. The project should also be configurable or a little hint in the documentation will help others.

The RenderingHelper.php contains a baseurl parameter, which is static & not configurable:

```
public function linkToJira($caption, $url, $attributes = [])
    {
        $baseUrl = 'THIS SHOULD BE CONFIGURABLE';
        if (is_array($url)) {
            $baseUrl .= array_shift($url)
```

The IssueDetails.php refer to a property which is not defined in documentation (probably a custom field missing):

```
protected function assemble()
    {
        $helper = $this->helper;
        $issue = $this->issue;
        $key = $issue->key;

        $fields = $issue->fields;
        $projectKey = $fields->project->key;

        $icingaKey = preg_replace('/^BEGIN(.+)END$/', '$1', $fields->icingaKey);
        $parts = explode('!', $icingaKey);
        $host = array_shift($parts);
        if (empty($parts)) {
            $service = null;
        } else {
            $service = array_shift($parts);
        }
        $user = $fields->icingaUser; <-- THROWS ERROR
```

I got that figured out & want to say THANK YOU! Great work!

**Comment by Thomas-Gelf** [comment]
@jprusch: thanks a lot for your feedback, especially for `resolution IS EMPTY` - this really helped. And sorry for the delay. Now I'm finally allowed to dedicate some time to this module.

**Comment by Thomas-Gelf** [comment]
NB: all your points should have been addressed, if I missed something please let me know!
